### ISSUE TITLE
Собрать страницу формы

### ISSUE THREAD

**Issue by isqua** [alex-koshara/pink-2#38]
Что надо сделать до того, как собирать страницу формы:

- [ ] Сверстать input #1
- [x] Сверстать radio #2
- [x] Сверстать checkbox #3 
- [ ] Сверстать textarea #4
- [ ] Сверстать btn #5
- [ ] Сверстать main-nav #8
- [ ] Сверстать логотип #9
- [ ] Сверстать copyright #10
- [ ] Сверстать заголовок страницы #22
- [ ] Сверстать иконки социальных сетей #24
- [ ] Сверстать подвал (про него нет задачи!)

Что можно сделать сразу на странице формы:

- [ ] Тебе понадобится какой-то [блок-центровщик](https://isqua.ru/blog/2016/06/23/content-po-sentru-fon-po-shirinie/), сделай его отдельным коммитом во время вёрстки всей страницы.
- [ ] Сверстать подпись к форме #23
- [ ] Сверстать приписку к форме #36

Что можно сделать после того, как сделаешь страницу формы:

- [ ] Сверстать попапы и сделать, чтобы они показывались (про это нет задачи!)

**Comment by alex-koshara** [comment]
а я думал на счет подвала, и к чему пришел: это же просто семантический блок, в котором хранятся другие блоки, которые обычно находятся внизу страницы. Т.е. разметить его сразу, когда буду добавлять на страницу компоненты. Мол header, main, footer, section, article и другие крупные сеточные блоки. Или не?

**Comment by isqua** [comment]
> это же просто семантический блок

Что это значит? Что у него нет своего CSS?
