### ISSUE TITLE
Собрать главную страницу

### ISSUE THREAD

**Issue by isqua** [alex-koshara/pink-2#39]
Предлагаю сначала сделать вот эти блоки:

- [ ] Сверстать main-nav #8
- [ ] Сверстать логотип #9
- [ ] Сверстать copyright #10
- [ ] Сверстать заголовок страницы #22
- [ ] Сверстать иконки социальных сетей #24
- [ ] Сверстать подвал (про него нет задачи!)

Потом запилить пулл-реквест, где эти блоки подключаются в index.pug, его отревьювить и влить. 
И потом можно прямо на этой странице верстать следующие блоки:

- [ ] Сверстать контакты #25
- [ ] Сверстать карту #26
- [ ] Сверстать преимущества PINK #27
- [ ] Сверстать доступные операционки #28
- [ ] Сверстать блок с исследованиями #29
- [ ] Сверстать блок с отзывами #30
- [ ] Сверстать кнопки управления #31
- [ ] Сверстать блок стоимости #32
